package com.luci.aeris.constants

class StringConstants {
    companion object {
        const val title = "Aeris"
        const val gender = "Cinsiyet"
        const val signUp= "Sing Up"
        const val email="Email"
        const val password="Password"
        const val validEmail="Please enter a valid email"
        const val createPassword=  "Create Password"
        const val passwordRule= "Password must be at least 6 characters"
        const val confirmPassword= "Confirm Password"
        const val passwordDoesntMatch="Passwords do not match"
        const val termsAndPolicy="By Signing Up, you agree to our\nTerms & Privacy Policy"
        const val or="or"
        const val alreadyHaveAccount= "Already have an account?"
        const val dontHaveAccount="Don't have an account?"
        const val login="Login"
        const val successRegister="You have successfully registered."
        const val close="Close"
        const val somethingWentWrong="Something went wrong"
        const val somethingWentWrongOnGoogle="Something went wrong on Google Sign Up"
        const val googleLogo="Google Logo"
        const val signUpWithGoogle= "Sign Up With Google"
        const val loginWithGoogle= "Log In With Google"
        const val guest="Guest"
        const val guestMail="guest@gmail.com"
        const val failToCreateUser= "Firestore register is failed"
        const val successLogin="You have successfully login."
        const val main="Main"
        const val outfit="Outfit"
        const val add="Add"
        const val wardrobe="Wardrobe"
        const val profile="Profile"
    }
}